### ISSUE TITLE
Error! App '232250' state is 0x402 after update job.

### ISSUE THREAD

**Issue by kaihendry** [Gonzih/docker-tf2-server#4]
https://twitter.com/Gonzih/status/731009199224836096

```
 Update state (0x61) downloading, progress: 3.93 (233774822 / 5953327306)
 Update state (0x61) downloading, progress: 3.93 (233774822 / 5953327306)
 Update state (0x61) downloading, progress: 3.93 (233774822 / 5953327306)
 Update state (0x61) downloading, progress: 3.93 (233774822 / 5953327306)
 Update state (0x61) downloading, progress: 3.93 (233774822 / 5953327306)
Error! App '232250' state is 0x402 after update job.
quit
 ---> cba84010045c
Removing intermediate container 396df713b7f9
Step 20 : EXPOSE 27015/udp
 ---> Running in c91082458d41
 ---> 1d91428026dd
Removing intermediate container c91082458d41
Step 21 : WORKDIR /home/$USER/hlserver
 ---> Running in 4b45c12c6857
 ---> 26ec05feb73e
Removing intermediate container 4b45c12c6857
Step 22 : ENTRYPOINT ./tf.sh
 ---> Running in 352ef793aa85
 ---> a07735bbdcb4
Removing intermediate container 352ef793aa85
Step 23 : CMD +sv_pure 1 +mapcycle mapcycle_quickplay_payload.txt +map pl_badwater +maxplayers 24
 ---> Running in 59a750c8862c
 ---> 6b8344ea8df2
Removing intermediate container 59a750c8862c
Successfully built 6b8344ea8df2
nuc:~/tmp/docker-tf2-server$
```

I think the problem here is that there is some download issue and I basically have an incomplete image.

Docker should ideally be able to detect the failure and retry maybe?

Not sure what the correct approach is here.

**Comment by Gonzih** [comment]
Looks like network issue on your side. Steam does not return error exit codes, everything is 0 so docker thinks things went well. I pushed pre-built image to the docker hub. Just use `gonzih/tf2-server` image (docker pull mechanism should be more reliable than steam download). Tell me if that helps.

Cheers!

**Comment by kaihendry** [comment]
How does one keep the image uptodate? Is that you doing it and I pull from time to time?

**Comment by Gonzih** [comment]
When you start the server it will check for updates and apply them. It will also apply any updates when server is running.

**Comment by kaihendry** [comment]
Thank you!
